"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.block = void 0;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.3
 * source: proto-block.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
var dependency_1 = __importStar(require("./proto_common"));
var pb_1 = __importStar(require("google-protobuf"));
var block;
(function (block) {
    var ProtoTransaction = /** @class */ (function (_super) {
        __extends(ProtoTransaction, _super);
        function ProtoTransaction(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23], [24]];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("type" in data && data.type != undefined) {
                    _this.type = data.type;
                }
                if ("to" in data && data.to != undefined) {
                    _this.to = data.to;
                }
                if ("nonce" in data && data.nonce != undefined) {
                    _this.nonce = data.nonce;
                }
                if ("value" in data && data.value != undefined) {
                    _this.value = data.value;
                }
                if ("gas" in data && data.gas != undefined) {
                    _this.gas = data.gas;
                }
                if ("data" in data && data.data != undefined) {
                    _this.data = data.data;
                }
                if ("chain_id" in data && data.chain_id != undefined) {
                    _this.chain_id = data.chain_id;
                }
                if ("gas_fee_cap" in data && data.gas_fee_cap != undefined) {
                    _this.gas_fee_cap = data.gas_fee_cap;
                }
                if ("gas_tip_cap" in data && data.gas_tip_cap != undefined) {
                    _this.gas_tip_cap = data.gas_tip_cap;
                }
                if ("access_list" in data && data.access_list != undefined) {
                    _this.access_list = data.access_list;
                }
                if ("etx_gas_limit" in data && data.etx_gas_limit != undefined) {
                    _this.etx_gas_limit = data.etx_gas_limit;
                }
                if ("etx_gas_price" in data && data.etx_gas_price != undefined) {
                    _this.etx_gas_price = data.etx_gas_price;
                }
                if ("etx_gas_tip" in data && data.etx_gas_tip != undefined) {
                    _this.etx_gas_tip = data.etx_gas_tip;
                }
                if ("etx_data" in data && data.etx_data != undefined) {
                    _this.etx_data = data.etx_data;
                }
                if ("etx_access_list" in data && data.etx_access_list != undefined) {
                    _this.etx_access_list = data.etx_access_list;
                }
                if ("v" in data && data.v != undefined) {
                    _this.v = data.v;
                }
                if ("r" in data && data.r != undefined) {
                    _this.r = data.r;
                }
                if ("s" in data && data.s != undefined) {
                    _this.s = data.s;
                }
                if ("originating_tx_hash" in data && data.originating_tx_hash != undefined) {
                    _this.originating_tx_hash = data.originating_tx_hash;
                }
                if ("etx_index" in data && data.etx_index != undefined) {
                    _this.etx_index = data.etx_index;
                }
                if ("etx_sender" in data && data.etx_sender != undefined) {
                    _this.etx_sender = data.etx_sender;
                }
                if ("tx_ins" in data && data.tx_ins != undefined) {
                    _this.tx_ins = data.tx_ins;
                }
                if ("tx_outs" in data && data.tx_outs != undefined) {
                    _this.tx_outs = data.tx_outs;
                }
                if ("signature" in data && data.signature != undefined) {
                    _this.signature = data.signature;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoTransaction.prototype, "type", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 1, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 1, this.one_of_decls[0], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_type", {
            get: function () {
                return pb_1.Message.getField(this, 1) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "to", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 2, this.one_of_decls[1], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_to", {
            get: function () {
                return pb_1.Message.getField(this, 2) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "nonce", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 3, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 3, this.one_of_decls[2], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_nonce", {
            get: function () {
                return pb_1.Message.getField(this, 3) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "value", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 4, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 4, this.one_of_decls[3], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_value", {
            get: function () {
                return pb_1.Message.getField(this, 4) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "gas", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 5, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 5, this.one_of_decls[4], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_gas", {
            get: function () {
                return pb_1.Message.getField(this, 5) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "data", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 6, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 6, this.one_of_decls[5], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_data", {
            get: function () {
                return pb_1.Message.getField(this, 6) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "chain_id", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 7, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 7, this.one_of_decls[6], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_chain_id", {
            get: function () {
                return pb_1.Message.getField(this, 7) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "gas_fee_cap", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 8, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 8, this.one_of_decls[7], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_gas_fee_cap", {
            get: function () {
                return pb_1.Message.getField(this, 8) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "gas_tip_cap", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 9, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 9, this.one_of_decls[8], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_gas_tip_cap", {
            get: function () {
                return pb_1.Message.getField(this, 9) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "access_list", {
            get: function () {
                return pb_1.Message.getWrapperField(this, ProtoAccessList, 10);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 10, this.one_of_decls[9], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_access_list", {
            get: function () {
                return pb_1.Message.getField(this, 10) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_gas_limit", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 11, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 11, this.one_of_decls[10], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_gas_limit", {
            get: function () {
                return pb_1.Message.getField(this, 11) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_gas_price", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 12, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 12, this.one_of_decls[11], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_gas_price", {
            get: function () {
                return pb_1.Message.getField(this, 12) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_gas_tip", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 13, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 13, this.one_of_decls[12], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_gas_tip", {
            get: function () {
                return pb_1.Message.getField(this, 13) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_data", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 14, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 14, this.one_of_decls[13], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_data", {
            get: function () {
                return pb_1.Message.getField(this, 14) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_access_list", {
            get: function () {
                return pb_1.Message.getWrapperField(this, ProtoAccessList, 15);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 15, this.one_of_decls[14], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_access_list", {
            get: function () {
                return pb_1.Message.getField(this, 15) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "v", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 16, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 16, this.one_of_decls[15], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_v", {
            get: function () {
                return pb_1.Message.getField(this, 16) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "r", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 17, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 17, this.one_of_decls[16], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_r", {
            get: function () {
                return pb_1.Message.getField(this, 17) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "s", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 18, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 18, this.one_of_decls[17], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_s", {
            get: function () {
                return pb_1.Message.getField(this, 18) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "originating_tx_hash", {
            get: function () {
                return pb_1.Message.getWrapperField(this, dependency_1.common.ProtoHash, 19);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 19, this.one_of_decls[18], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_originating_tx_hash", {
            get: function () {
                return pb_1.Message.getField(this, 19) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_index", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 20, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 20, this.one_of_decls[19], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_index", {
            get: function () {
                return pb_1.Message.getField(this, 20) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "etx_sender", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 21, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 21, this.one_of_decls[20], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_etx_sender", {
            get: function () {
                return pb_1.Message.getField(this, 21) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "tx_ins", {
            get: function () {
                return pb_1.Message.getWrapperField(this, ProtoTxIns, 22);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 22, this.one_of_decls[21], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_tx_ins", {
            get: function () {
                return pb_1.Message.getField(this, 22) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "tx_outs", {
            get: function () {
                return pb_1.Message.getWrapperField(this, ProtoTxOuts, 23);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 23, this.one_of_decls[22], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_tx_outs", {
            get: function () {
                return pb_1.Message.getField(this, 23) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "signature", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 24, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 24, this.one_of_decls[23], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "has_signature", {
            get: function () {
                return pb_1.Message.getField(this, 24) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_type", {
            get: function () {
                var cases = {
                    0: "none",
                    1: "type"
                };
                return cases[pb_1.Message.computeOneofCase(this, [1])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_to", {
            get: function () {
                var cases = {
                    0: "none",
                    2: "to"
                };
                return cases[pb_1.Message.computeOneofCase(this, [2])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_nonce", {
            get: function () {
                var cases = {
                    0: "none",
                    3: "nonce"
                };
                return cases[pb_1.Message.computeOneofCase(this, [3])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_value", {
            get: function () {
                var cases = {
                    0: "none",
                    4: "value"
                };
                return cases[pb_1.Message.computeOneofCase(this, [4])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_gas", {
            get: function () {
                var cases = {
                    0: "none",
                    5: "gas"
                };
                return cases[pb_1.Message.computeOneofCase(this, [5])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_data", {
            get: function () {
                var cases = {
                    0: "none",
                    6: "data"
                };
                return cases[pb_1.Message.computeOneofCase(this, [6])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_chain_id", {
            get: function () {
                var cases = {
                    0: "none",
                    7: "chain_id"
                };
                return cases[pb_1.Message.computeOneofCase(this, [7])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_gas_fee_cap", {
            get: function () {
                var cases = {
                    0: "none",
                    8: "gas_fee_cap"
                };
                return cases[pb_1.Message.computeOneofCase(this, [8])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_gas_tip_cap", {
            get: function () {
                var cases = {
                    0: "none",
                    9: "gas_tip_cap"
                };
                return cases[pb_1.Message.computeOneofCase(this, [9])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_access_list", {
            get: function () {
                var cases = {
                    0: "none",
                    10: "access_list"
                };
                return cases[pb_1.Message.computeOneofCase(this, [10])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_gas_limit", {
            get: function () {
                var cases = {
                    0: "none",
                    11: "etx_gas_limit"
                };
                return cases[pb_1.Message.computeOneofCase(this, [11])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_gas_price", {
            get: function () {
                var cases = {
                    0: "none",
                    12: "etx_gas_price"
                };
                return cases[pb_1.Message.computeOneofCase(this, [12])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_gas_tip", {
            get: function () {
                var cases = {
                    0: "none",
                    13: "etx_gas_tip"
                };
                return cases[pb_1.Message.computeOneofCase(this, [13])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_data", {
            get: function () {
                var cases = {
                    0: "none",
                    14: "etx_data"
                };
                return cases[pb_1.Message.computeOneofCase(this, [14])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_access_list", {
            get: function () {
                var cases = {
                    0: "none",
                    15: "etx_access_list"
                };
                return cases[pb_1.Message.computeOneofCase(this, [15])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_v", {
            get: function () {
                var cases = {
                    0: "none",
                    16: "v"
                };
                return cases[pb_1.Message.computeOneofCase(this, [16])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_r", {
            get: function () {
                var cases = {
                    0: "none",
                    17: "r"
                };
                return cases[pb_1.Message.computeOneofCase(this, [17])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_s", {
            get: function () {
                var cases = {
                    0: "none",
                    18: "s"
                };
                return cases[pb_1.Message.computeOneofCase(this, [18])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_originating_tx_hash", {
            get: function () {
                var cases = {
                    0: "none",
                    19: "originating_tx_hash"
                };
                return cases[pb_1.Message.computeOneofCase(this, [19])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_index", {
            get: function () {
                var cases = {
                    0: "none",
                    20: "etx_index"
                };
                return cases[pb_1.Message.computeOneofCase(this, [20])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_etx_sender", {
            get: function () {
                var cases = {
                    0: "none",
                    21: "etx_sender"
                };
                return cases[pb_1.Message.computeOneofCase(this, [21])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_tx_ins", {
            get: function () {
                var cases = {
                    0: "none",
                    22: "tx_ins"
                };
                return cases[pb_1.Message.computeOneofCase(this, [22])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_tx_outs", {
            get: function () {
                var cases = {
                    0: "none",
                    23: "tx_outs"
                };
                return cases[pb_1.Message.computeOneofCase(this, [23])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTransaction.prototype, "_signature", {
            get: function () {
                var cases = {
                    0: "none",
                    24: "signature"
                };
                return cases[pb_1.Message.computeOneofCase(this, [24])];
            },
            enumerable: false,
            configurable: true
        });
        ProtoTransaction.fromObject = function (data) {
            var message = new ProtoTransaction({});
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.to != null) {
                message.to = data.to;
            }
            if (data.nonce != null) {
                message.nonce = data.nonce;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            if (data.gas != null) {
                message.gas = data.gas;
            }
            if (data.data != null) {
                message.data = data.data;
            }
            if (data.chain_id != null) {
                message.chain_id = data.chain_id;
            }
            if (data.gas_fee_cap != null) {
                message.gas_fee_cap = data.gas_fee_cap;
            }
            if (data.gas_tip_cap != null) {
                message.gas_tip_cap = data.gas_tip_cap;
            }
            if (data.access_list != null) {
                message.access_list = ProtoAccessList.fromObject(data.access_list);
            }
            if (data.etx_gas_limit != null) {
                message.etx_gas_limit = data.etx_gas_limit;
            }
            if (data.etx_gas_price != null) {
                message.etx_gas_price = data.etx_gas_price;
            }
            if (data.etx_gas_tip != null) {
                message.etx_gas_tip = data.etx_gas_tip;
            }
            if (data.etx_data != null) {
                message.etx_data = data.etx_data;
            }
            if (data.etx_access_list != null) {
                message.etx_access_list = ProtoAccessList.fromObject(data.etx_access_list);
            }
            if (data.v != null) {
                message.v = data.v;
            }
            if (data.r != null) {
                message.r = data.r;
            }
            if (data.s != null) {
                message.s = data.s;
            }
            if (data.originating_tx_hash != null) {
                message.originating_tx_hash = dependency_1.common.ProtoHash.fromObject(data.originating_tx_hash);
            }
            if (data.etx_index != null) {
                message.etx_index = data.etx_index;
            }
            if (data.etx_sender != null) {
                message.etx_sender = data.etx_sender;
            }
            if (data.tx_ins != null) {
                message.tx_ins = ProtoTxIns.fromObject(data.tx_ins);
            }
            if (data.tx_outs != null) {
                message.tx_outs = ProtoTxOuts.fromObject(data.tx_outs);
            }
            if (data.signature != null) {
                message.signature = data.signature;
            }
            return message;
        };
        ProtoTransaction.prototype.toObject = function () {
            var data = {};
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.to != null) {
                data.to = this.to;
            }
            if (this.nonce != null) {
                data.nonce = this.nonce;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            if (this.gas != null) {
                data.gas = this.gas;
            }
            if (this.data != null) {
                data.data = this.data;
            }
            if (this.chain_id != null) {
                data.chain_id = this.chain_id;
            }
            if (this.gas_fee_cap != null) {
                data.gas_fee_cap = this.gas_fee_cap;
            }
            if (this.gas_tip_cap != null) {
                data.gas_tip_cap = this.gas_tip_cap;
            }
            if (this.access_list != null) {
                data.access_list = this.access_list.toObject();
            }
            if (this.etx_gas_limit != null) {
                data.etx_gas_limit = this.etx_gas_limit;
            }
            if (this.etx_gas_price != null) {
                data.etx_gas_price = this.etx_gas_price;
            }
            if (this.etx_gas_tip != null) {
                data.etx_gas_tip = this.etx_gas_tip;
            }
            if (this.etx_data != null) {
                data.etx_data = this.etx_data;
            }
            if (this.etx_access_list != null) {
                data.etx_access_list = this.etx_access_list.toObject();
            }
            if (this.v != null) {
                data.v = this.v;
            }
            if (this.r != null) {
                data.r = this.r;
            }
            if (this.s != null) {
                data.s = this.s;
            }
            if (this.originating_tx_hash != null) {
                data.originating_tx_hash = this.originating_tx_hash.toObject();
            }
            if (this.etx_index != null) {
                data.etx_index = this.etx_index;
            }
            if (this.etx_sender != null) {
                data.etx_sender = this.etx_sender;
            }
            if (this.tx_ins != null) {
                data.tx_ins = this.tx_ins.toObject();
            }
            if (this.tx_outs != null) {
                data.tx_outs = this.tx_outs.toObject();
            }
            if (this.signature != null) {
                data.signature = this.signature;
            }
            return data;
        };
        ProtoTransaction.prototype.serialize = function (w) {
            var _this = this;
            var writer = w || new pb_1.BinaryWriter();
            if (this.has_type)
                writer.writeUint64(1, this.type);
            if (this.has_to)
                writer.writeBytes(2, this.to);
            if (this.has_nonce)
                writer.writeUint64(3, this.nonce);
            if (this.has_value)
                writer.writeBytes(4, this.value);
            if (this.has_gas)
                writer.writeUint64(5, this.gas);
            if (this.has_data)
                writer.writeBytes(6, this.data);
            if (this.has_chain_id)
                writer.writeBytes(7, this.chain_id);
            if (this.has_gas_fee_cap)
                writer.writeBytes(8, this.gas_fee_cap);
            if (this.has_gas_tip_cap)
                writer.writeBytes(9, this.gas_tip_cap);
            if (this.has_access_list)
                writer.writeMessage(10, this.access_list, function () { return _this.access_list.serialize(writer); });
            if (this.has_etx_gas_limit)
                writer.writeUint64(11, this.etx_gas_limit);
            if (this.has_etx_gas_price)
                writer.writeBytes(12, this.etx_gas_price);
            if (this.has_etx_gas_tip)
                writer.writeBytes(13, this.etx_gas_tip);
            if (this.has_etx_data)
                writer.writeBytes(14, this.etx_data);
            if (this.has_etx_access_list)
                writer.writeMessage(15, this.etx_access_list, function () { return _this.etx_access_list.serialize(writer); });
            if (this.has_v)
                writer.writeBytes(16, this.v);
            if (this.has_r)
                writer.writeBytes(17, this.r);
            if (this.has_s)
                writer.writeBytes(18, this.s);
            if (this.has_originating_tx_hash)
                writer.writeMessage(19, this.originating_tx_hash, function () { return _this.originating_tx_hash.serialize(writer); });
            if (this.has_etx_index)
                writer.writeUint32(20, this.etx_index);
            if (this.has_etx_sender)
                writer.writeBytes(21, this.etx_sender);
            if (this.has_tx_ins)
                writer.writeMessage(22, this.tx_ins, function () { return _this.tx_ins.serialize(writer); });
            if (this.has_tx_outs)
                writer.writeMessage(23, this.tx_outs, function () { return _this.tx_outs.serialize(writer); });
            if (this.has_signature)
                writer.writeBytes(24, this.signature);
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoTransaction.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoTransaction();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.type = reader.readUint64();
                        break;
                    case 2:
                        message.to = reader.readBytes();
                        break;
                    case 3:
                        message.nonce = reader.readUint64();
                        break;
                    case 4:
                        message.value = reader.readBytes();
                        break;
                    case 5:
                        message.gas = reader.readUint64();
                        break;
                    case 6:
                        message.data = reader.readBytes();
                        break;
                    case 7:
                        message.chain_id = reader.readBytes();
                        break;
                    case 8:
                        message.gas_fee_cap = reader.readBytes();
                        break;
                    case 9:
                        message.gas_tip_cap = reader.readBytes();
                        break;
                    case 10:
                        reader.readMessage(message.access_list, function () { return message.access_list = ProtoAccessList.deserialize(reader); });
                        break;
                    case 11:
                        message.etx_gas_limit = reader.readUint64();
                        break;
                    case 12:
                        message.etx_gas_price = reader.readBytes();
                        break;
                    case 13:
                        message.etx_gas_tip = reader.readBytes();
                        break;
                    case 14:
                        message.etx_data = reader.readBytes();
                        break;
                    case 15:
                        reader.readMessage(message.etx_access_list, function () { return message.etx_access_list = ProtoAccessList.deserialize(reader); });
                        break;
                    case 16:
                        message.v = reader.readBytes();
                        break;
                    case 17:
                        message.r = reader.readBytes();
                        break;
                    case 18:
                        message.s = reader.readBytes();
                        break;
                    case 19:
                        reader.readMessage(message.originating_tx_hash, function () { return message.originating_tx_hash = dependency_1.common.ProtoHash.deserialize(reader); });
                        break;
                    case 20:
                        message.etx_index = reader.readUint32();
                        break;
                    case 21:
                        message.etx_sender = reader.readBytes();
                        break;
                    case 22:
                        reader.readMessage(message.tx_ins, function () { return message.tx_ins = ProtoTxIns.deserialize(reader); });
                        break;
                    case 23:
                        reader.readMessage(message.tx_outs, function () { return message.tx_outs = ProtoTxOuts.deserialize(reader); });
                        break;
                    case 24:
                        message.signature = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoTransaction.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoTransaction.deserializeBinary = function (bytes) {
            return ProtoTransaction.deserialize(bytes);
        };
        return ProtoTransaction;
    }(pb_1.Message));
    block.ProtoTransaction = ProtoTransaction;
    var ProtoAccessList = /** @class */ (function (_super) {
        __extends(ProtoAccessList, _super);
        function ProtoAccessList(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [1], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("access_tuples" in data && data.access_tuples != undefined) {
                    _this.access_tuples = data.access_tuples;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoAccessList.prototype, "access_tuples", {
            get: function () {
                return pb_1.Message.getRepeatedWrapperField(this, ProtoAccessTuple, 1);
            },
            set: function (value) {
                pb_1.Message.setRepeatedWrapperField(this, 1, value);
            },
            enumerable: false,
            configurable: true
        });
        ProtoAccessList.fromObject = function (data) {
            var message = new ProtoAccessList({});
            if (data.access_tuples != null) {
                message.access_tuples = data.access_tuples.map(function (item) { return ProtoAccessTuple.fromObject(item); });
            }
            return message;
        };
        ProtoAccessList.prototype.toObject = function () {
            var data = {};
            if (this.access_tuples != null) {
                data.access_tuples = this.access_tuples.map(function (item) { return item.toObject(); });
            }
            return data;
        };
        ProtoAccessList.prototype.serialize = function (w) {
            var writer = w || new pb_1.BinaryWriter();
            if (this.access_tuples.length)
                writer.writeRepeatedMessage(1, this.access_tuples, function (item) { return item.serialize(writer); });
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoAccessList.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoAccessList();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.access_tuples, function () { return pb_1.Message.addToRepeatedWrapperField(message, 1, ProtoAccessTuple.deserialize(reader), ProtoAccessTuple); });
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoAccessList.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoAccessList.deserializeBinary = function (bytes) {
            return ProtoAccessList.deserialize(bytes);
        };
        return ProtoAccessList;
    }(pb_1.Message));
    block.ProtoAccessList = ProtoAccessList;
    var ProtoTxIns = /** @class */ (function (_super) {
        __extends(ProtoTxIns, _super);
        function ProtoTxIns(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [1], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("tx_ins" in data && data.tx_ins != undefined) {
                    _this.tx_ins = data.tx_ins;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoTxIns.prototype, "tx_ins", {
            get: function () {
                return pb_1.Message.getRepeatedWrapperField(this, ProtoTxIn, 1);
            },
            set: function (value) {
                pb_1.Message.setRepeatedWrapperField(this, 1, value);
            },
            enumerable: false,
            configurable: true
        });
        ProtoTxIns.fromObject = function (data) {
            var message = new ProtoTxIns({});
            if (data.tx_ins != null) {
                message.tx_ins = data.tx_ins.map(function (item) { return ProtoTxIn.fromObject(item); });
            }
            return message;
        };
        ProtoTxIns.prototype.toObject = function () {
            var data = {};
            if (this.tx_ins != null) {
                data.tx_ins = this.tx_ins.map(function (item) { return item.toObject(); });
            }
            return data;
        };
        ProtoTxIns.prototype.serialize = function (w) {
            var writer = w || new pb_1.BinaryWriter();
            if (this.tx_ins.length)
                writer.writeRepeatedMessage(1, this.tx_ins, function (item) { return item.serialize(writer); });
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoTxIns.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoTxIns();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.tx_ins, function () { return pb_1.Message.addToRepeatedWrapperField(message, 1, ProtoTxIn.deserialize(reader), ProtoTxIn); });
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoTxIns.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoTxIns.deserializeBinary = function (bytes) {
            return ProtoTxIns.deserialize(bytes);
        };
        return ProtoTxIns;
    }(pb_1.Message));
    block.ProtoTxIns = ProtoTxIns;
    var ProtoTxOuts = /** @class */ (function (_super) {
        __extends(ProtoTxOuts, _super);
        function ProtoTxOuts(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [1], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("tx_outs" in data && data.tx_outs != undefined) {
                    _this.tx_outs = data.tx_outs;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoTxOuts.prototype, "tx_outs", {
            get: function () {
                return pb_1.Message.getRepeatedWrapperField(this, ProtoTxOut, 1);
            },
            set: function (value) {
                pb_1.Message.setRepeatedWrapperField(this, 1, value);
            },
            enumerable: false,
            configurable: true
        });
        ProtoTxOuts.fromObject = function (data) {
            var message = new ProtoTxOuts({});
            if (data.tx_outs != null) {
                message.tx_outs = data.tx_outs.map(function (item) { return ProtoTxOut.fromObject(item); });
            }
            return message;
        };
        ProtoTxOuts.prototype.toObject = function () {
            var data = {};
            if (this.tx_outs != null) {
                data.tx_outs = this.tx_outs.map(function (item) { return item.toObject(); });
            }
            return data;
        };
        ProtoTxOuts.prototype.serialize = function (w) {
            var writer = w || new pb_1.BinaryWriter();
            if (this.tx_outs.length)
                writer.writeRepeatedMessage(1, this.tx_outs, function (item) { return item.serialize(writer); });
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoTxOuts.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoTxOuts();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.tx_outs, function () { return pb_1.Message.addToRepeatedWrapperField(message, 1, ProtoTxOut.deserialize(reader), ProtoTxOut); });
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoTxOuts.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoTxOuts.deserializeBinary = function (bytes) {
            return ProtoTxOuts.deserialize(bytes);
        };
        return ProtoTxOuts;
    }(pb_1.Message));
    block.ProtoTxOuts = ProtoTxOuts;
    var ProtoTxIn = /** @class */ (function (_super) {
        __extends(ProtoTxIn, _super);
        function ProtoTxIn(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [[1], [2]];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("previous_out_point" in data && data.previous_out_point != undefined) {
                    _this.previous_out_point = data.previous_out_point;
                }
                if ("pub_key" in data && data.pub_key != undefined) {
                    _this.pub_key = data.pub_key;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoTxIn.prototype, "previous_out_point", {
            get: function () {
                return pb_1.Message.getWrapperField(this, ProtoOutPoint, 1);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 1, this.one_of_decls[0], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxIn.prototype, "has_previous_out_point", {
            get: function () {
                return pb_1.Message.getField(this, 1) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxIn.prototype, "pub_key", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 2, this.one_of_decls[1], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxIn.prototype, "has_pub_key", {
            get: function () {
                return pb_1.Message.getField(this, 2) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxIn.prototype, "_previous_out_point", {
            get: function () {
                var cases = {
                    0: "none",
                    1: "previous_out_point"
                };
                return cases[pb_1.Message.computeOneofCase(this, [1])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxIn.prototype, "_pub_key", {
            get: function () {
                var cases = {
                    0: "none",
                    2: "pub_key"
                };
                return cases[pb_1.Message.computeOneofCase(this, [2])];
            },
            enumerable: false,
            configurable: true
        });
        ProtoTxIn.fromObject = function (data) {
            var message = new ProtoTxIn({});
            if (data.previous_out_point != null) {
                message.previous_out_point = ProtoOutPoint.fromObject(data.previous_out_point);
            }
            if (data.pub_key != null) {
                message.pub_key = data.pub_key;
            }
            return message;
        };
        ProtoTxIn.prototype.toObject = function () {
            var data = {};
            if (this.previous_out_point != null) {
                data.previous_out_point = this.previous_out_point.toObject();
            }
            if (this.pub_key != null) {
                data.pub_key = this.pub_key;
            }
            return data;
        };
        ProtoTxIn.prototype.serialize = function (w) {
            var _this = this;
            var writer = w || new pb_1.BinaryWriter();
            if (this.has_previous_out_point)
                writer.writeMessage(1, this.previous_out_point, function () { return _this.previous_out_point.serialize(writer); });
            if (this.has_pub_key)
                writer.writeBytes(2, this.pub_key);
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoTxIn.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoTxIn();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.previous_out_point, function () { return message.previous_out_point = ProtoOutPoint.deserialize(reader); });
                        break;
                    case 2:
                        message.pub_key = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoTxIn.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoTxIn.deserializeBinary = function (bytes) {
            return ProtoTxIn.deserialize(bytes);
        };
        return ProtoTxIn;
    }(pb_1.Message));
    block.ProtoTxIn = ProtoTxIn;
    var ProtoOutPoint = /** @class */ (function (_super) {
        __extends(ProtoOutPoint, _super);
        function ProtoOutPoint(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [[1], [2]];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("hash" in data && data.hash != undefined) {
                    _this.hash = data.hash;
                }
                if ("index" in data && data.index != undefined) {
                    _this.index = data.index;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoOutPoint.prototype, "hash", {
            get: function () {
                return pb_1.Message.getWrapperField(this, dependency_1.common.ProtoHash, 1);
            },
            set: function (value) {
                pb_1.Message.setOneofWrapperField(this, 1, this.one_of_decls[0], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoOutPoint.prototype, "has_hash", {
            get: function () {
                return pb_1.Message.getField(this, 1) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoOutPoint.prototype, "index", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 2, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 2, this.one_of_decls[1], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoOutPoint.prototype, "has_index", {
            get: function () {
                return pb_1.Message.getField(this, 2) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoOutPoint.prototype, "_hash", {
            get: function () {
                var cases = {
                    0: "none",
                    1: "hash"
                };
                return cases[pb_1.Message.computeOneofCase(this, [1])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoOutPoint.prototype, "_index", {
            get: function () {
                var cases = {
                    0: "none",
                    2: "index"
                };
                return cases[pb_1.Message.computeOneofCase(this, [2])];
            },
            enumerable: false,
            configurable: true
        });
        ProtoOutPoint.fromObject = function (data) {
            var message = new ProtoOutPoint({});
            if (data.hash != null) {
                message.hash = dependency_1.common.ProtoHash.fromObject(data.hash);
            }
            if (data.index != null) {
                message.index = data.index;
            }
            return message;
        };
        ProtoOutPoint.prototype.toObject = function () {
            var data = {};
            if (this.hash != null) {
                data.hash = this.hash.toObject();
            }
            if (this.index != null) {
                data.index = this.index;
            }
            return data;
        };
        ProtoOutPoint.prototype.serialize = function (w) {
            var _this = this;
            var writer = w || new pb_1.BinaryWriter();
            if (this.has_hash)
                writer.writeMessage(1, this.hash, function () { return _this.hash.serialize(writer); });
            if (this.has_index)
                writer.writeUint32(2, this.index);
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoOutPoint.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoOutPoint();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.hash, function () { return message.hash = dependency_1.common.ProtoHash.deserialize(reader); });
                        break;
                    case 2:
                        message.index = reader.readUint32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoOutPoint.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoOutPoint.deserializeBinary = function (bytes) {
            return ProtoOutPoint.deserialize(bytes);
        };
        return ProtoOutPoint;
    }(pb_1.Message));
    block.ProtoOutPoint = ProtoOutPoint;
    var ProtoTxOut = /** @class */ (function (_super) {
        __extends(ProtoTxOut, _super);
        function ProtoTxOut(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [[1], [2]];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("denomination" in data && data.denomination != undefined) {
                    _this.denomination = data.denomination;
                }
                if ("address" in data && data.address != undefined) {
                    _this.address = data.address;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoTxOut.prototype, "denomination", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 1, 0);
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 1, this.one_of_decls[0], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxOut.prototype, "has_denomination", {
            get: function () {
                return pb_1.Message.getField(this, 1) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxOut.prototype, "address", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setOneofField(this, 2, this.one_of_decls[1], value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxOut.prototype, "has_address", {
            get: function () {
                return pb_1.Message.getField(this, 2) != null;
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxOut.prototype, "_denomination", {
            get: function () {
                var cases = {
                    0: "none",
                    1: "denomination"
                };
                return cases[pb_1.Message.computeOneofCase(this, [1])];
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoTxOut.prototype, "_address", {
            get: function () {
                var cases = {
                    0: "none",
                    2: "address"
                };
                return cases[pb_1.Message.computeOneofCase(this, [2])];
            },
            enumerable: false,
            configurable: true
        });
        ProtoTxOut.fromObject = function (data) {
            var message = new ProtoTxOut({});
            if (data.denomination != null) {
                message.denomination = data.denomination;
            }
            if (data.address != null) {
                message.address = data.address;
            }
            return message;
        };
        ProtoTxOut.prototype.toObject = function () {
            var data = {};
            if (this.denomination != null) {
                data.denomination = this.denomination;
            }
            if (this.address != null) {
                data.address = this.address;
            }
            return data;
        };
        ProtoTxOut.prototype.serialize = function (w) {
            var writer = w || new pb_1.BinaryWriter();
            if (this.has_denomination)
                writer.writeUint32(1, this.denomination);
            if (this.has_address)
                writer.writeBytes(2, this.address);
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoTxOut.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoTxOut();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.denomination = reader.readUint32();
                        break;
                    case 2:
                        message.address = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoTxOut.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoTxOut.deserializeBinary = function (bytes) {
            return ProtoTxOut.deserialize(bytes);
        };
        return ProtoTxOut;
    }(pb_1.Message));
    block.ProtoTxOut = ProtoTxOut;
    var ProtoAccessTuple = /** @class */ (function (_super) {
        __extends(ProtoAccessTuple, _super);
        function ProtoAccessTuple(data) {
            var _this = _super.call(this) || this;
            _this.one_of_decls = [];
            pb_1.Message.initialize(_this, Array.isArray(data) ? data : [], 0, -1, [2], _this.one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("address" in data && data.address != undefined) {
                    _this.address = data.address;
                }
                if ("storage_key" in data && data.storage_key != undefined) {
                    _this.storage_key = data.storage_key;
                }
            }
            return _this;
        }
        Object.defineProperty(ProtoAccessTuple.prototype, "address", {
            get: function () {
                return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0));
            },
            set: function (value) {
                pb_1.Message.setField(this, 1, value);
            },
            enumerable: false,
            configurable: true
        });
        Object.defineProperty(ProtoAccessTuple.prototype, "storage_key", {
            get: function () {
                return pb_1.Message.getRepeatedWrapperField(this, dependency_1.common.ProtoHash, 2);
            },
            set: function (value) {
                pb_1.Message.setRepeatedWrapperField(this, 2, value);
            },
            enumerable: false,
            configurable: true
        });
        ProtoAccessTuple.fromObject = function (data) {
            var message = new ProtoAccessTuple({});
            if (data.address != null) {
                message.address = data.address;
            }
            if (data.storage_key != null) {
                message.storage_key = data.storage_key.map(function (item) { return dependency_1.common.ProtoHash.fromObject(item); });
            }
            return message;
        };
        ProtoAccessTuple.prototype.toObject = function () {
            var data = {};
            if (this.address != null) {
                data.address = this.address;
            }
            if (this.storage_key != null) {
                data.storage_key = this.storage_key.map(function (item) { return item.toObject(); });
            }
            return data;
        };
        ProtoAccessTuple.prototype.serialize = function (w) {
            var writer = w || new pb_1.BinaryWriter();
            if (this.address.length)
                writer.writeBytes(1, this.address);
            if (this.storage_key.length)
                writer.writeRepeatedMessage(2, this.storage_key, function (item) { return item.serialize(writer); });
            if (!w)
                return writer.getResultBuffer();
        };
        ProtoAccessTuple.deserialize = function (bytes) {
            var reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProtoAccessTuple();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.address = reader.readBytes();
                        break;
                    case 2:
                        reader.readMessage(message.storage_key, function () { return pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_1.common.ProtoHash.deserialize(reader), dependency_1.common.ProtoHash); });
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        };
        ProtoAccessTuple.prototype.serializeBinary = function () {
            return this.serialize();
        };
        ProtoAccessTuple.deserializeBinary = function (bytes) {
            return ProtoAccessTuple.deserialize(bytes);
        };
        return ProtoAccessTuple;
    }(pb_1.Message));
    block.ProtoAccessTuple = ProtoAccessTuple;
})(block || (exports.block = block = {}));
//# sourceMappingURL=proto-block.js.map